### ISSUE TITLE
Should I modify IDs etc to make my firmware secure?

### ISSUE THREAD

**Issue by Thv1337** [ekknod/pcileech-wifi#10]
Basically everything indicated by pcileech-fpga + enable autoclear etc...
I am also wondering if with your firmware it is possible to modify blocks 40-90 of the config space.

Thank you.

**Comment by xCreez** [comment]
I was about to open a similar issue, i am wondering about this aswell!

**Comment by ekknod** [comment]
Please stop direct copy pasting and learn. You both completely lost.

**Comment by Thv1337** [comment]
We will have to learn but you are a complete human ruin. Close again this shit.

**Comment by ekknod** [comment]
Wrong mindset. You guys have chance to learn, instead "have to".
