### ISSUE TITLE
Device Info: FPGA: Bad PCIe TLP received! Should not happen!

### ISSUE THREAD

**Issue by Supergun777** [ekknod/pcileech-wifi#11]
Hello. I compiled and flashed the board without changing the code, and it gives me an error within a minute of work:
Device Info: FPGA: Bad PCIe TLP received! Should not happen!

Windows 11 Pro 22H2 22621.2861
11th Gen Intel(R) Core(TM) i5-11600K
Gigabyte Z590 GAMING X(rev. 1.0) Bios latest

**Comment by Supergun777** [comment]
[HOMEZZZ.LOG](https://github.com/ekknod/pcileech-wifi/files/13798740/HOMEZZZ.LOG)

**Comment by Supergun777** [comment]
[Uploading HOMEZZZ1.LOG…]()

**Comment by Supergun777** [comment]
[HOMEZZZ1.LOG](https://github.com/ekknod/pcileech-wifi/files/13798768/HOMEZZZ1.LOG)

**Comment by Supergun777** [comment]
[HOMEZZZ.LOG](https://github.com/ekknod/pcileech-wifi/files/13798777/HOMEZZZ.LOG)

**Comment by Supergun777** [comment]
I solved the problem, you just need to turn off Wi-Fi in the tray next to the clock.

**Comment by ekknod** [comment]
Core is now updated Version. 4.13. Issue should be now fixed. Disable WIFI from system tray in case you have TLP misses.
