### ISSUE TITLE
Am i missing the main config file ?

### ISSUE THREAD

**Issue by Youssix** [ekknod/pcileech-wifi#2]
Hello,

Have a quick question, normally with my other firmware i do have a pcie_7x_0.xci which allow me to configure a lot of things.

![image](https://github.com/ekknod/pcileech-wifi/assets/16267835/ca37f2f0-40c6-4475-96b2-a13e0fa3ed4f)

But with this firmware, after building i don't have this file.

![image](https://github.com/ekknod/pcileech-wifi/assets/16267835/3e9964fa-f458-4a7d-aaed-e6f3be6faccb)

Maybe it is because i'm using vivado 2023 ?

**Comment by F0RSV1NNA** [comment]
hey, i realize there isn't a ton of info out there about this, but this is a modified source from the original ulffrisk FPGA source.
you have full control over the config space with this source. edit everything with something like visual studio code (you can search for what you want to modify. as that config file no longer exists in this repo's source to put it simply.

**Comment by ekknod** [comment]
Thanks F0RSV1NNA for your answer, accurate. I was busy with AMD support update.
