### ISSUE TITLE
请问如何生成Captain 35T？

### ISSUE THREAD

**Issue by BaileyZyp** [ekknod/pcileech-wifi#20]
您好作者，我想问下该如何生成Captain 35T的固件我看到仓库中只有75T的代码，另外请问作者是否有PayPal的捐赠方式 我是一位来之中国的朋友没有虚拟货币钱包

**Comment by faxvs** [comment]
do u want sell it ?

**Comment by CalvinXu17** [comment]
I know many Chinese try to sell this firmware. If you really want to sponsor, please use English.
