### ISSUE TITLE
Intermittent failures with MemProcFs

### ISSUE THREAD

**Issue by KernelKrusha** [ekknod/pcileech-wifi#3]
Using MemProcFS, the latest version of the firmware on Intel i9-10850k (Z490) results in intermittent failures.

Log output:
`Device Info: FPGA: Bad PCIe TLP received! Should not happen!`

Other than this, it seems to be working perfectly.

**Comment by AAigars** [comment]
Seem to be having an issue where the DMA card is unable to process any read/write operations for a few minutes at random intervals. Thought maybe it was something wrong with my setup or code but I flashed the original PCILeech firmware and I did not encounter this issue.

**Comment by fortnitebott** [comment]
Same for me. Dma stop work for a few seconds after a certain number of seconds.  I think it's because of the network card driver. It has a Wi-Fi update interval setting.

**Comment by ekknod** [comment]
> Same for me. Dma stop work for a few seconds after a certain number of seconds. I think it's because of the Qualcomm wireless card driver. It has a Wi-Fi update interval setting.

That's accurate. Multiplexer prefers signal from PCIe over FT601 currently.

**Comment by jordandadams** [comment]
Could the DeviceID be why it's not passing Vanguard? Possibly a different device work?

**Comment by ironman97** [comment]
So is there any better way to solve this problem?

**Comment by ekknod** [comment]
is this actually problem?

**Comment by ekknod** [comment]
is this actually problem?
it prefers device driver requests over FT601,

**Comment by ekknod** [comment]
is this actually problem? it prefers device driver requests over FT601 on purpose.

**Comment by AAigars** [comment]
> is this actually problem? it prefers device driver requests over FT601 on purpose.

Yeah, it made the firmware unusable for me. My read operation were taking way too long at certain times.

**Comment by AboutElse** [comment]
About 
`Device Info: FPGA: Bad PCIe TLP received! Should not happen!`

I found that only the Intel (13900KS+Z790) platform will display these errors, and AMD (5950X+X570) seems to be work fine.

**Comment by Alienccc** [comment]
> 大约 `Device Info: FPGA: Bad PCIe TLP received! Should not happen!`
> 
> 我发现只有Intel（13900KS+Z790）平台才会显示这些错误，而AMD（5950X+X570）似乎工作正常。

5900X+B550   This problem still occurs

**Comment by uk0** [comment]
Z690 update bios  nice job.

**Comment by ekknod** [comment]
Core is now updated Version. 4.13. Issue should be now fixed. Disable WIFI from system tray in case you have TLP misses.
