### ISSUE TITLE
fun - hooker source-code

### ISSUE THREAD

**Issue by get1n** [ekknod/pcileech-wifi#5]
First of all nice release @ekknod :)

I tried to run your fun - hooker but unfortunately it doens't work; After reinstalling driver it only prints out 640_done:
![fun - hooker_not woorking](https://github.com/ekknod/pcileech-wifi/assets/99487159/1a6bfb46-5e36-47d8-b4e5-4131857ef5a2)

settings are:
Capture kernel, Enable verbose, Pass-Through and Capture events.

What am I missing?

**Comment by dom0ng** [comment]
@get1n 

You need to create this key to see additional informations.

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Debug Print Filter The set the Default Value to 0xf. 

![image](https://github.com/ekknod/pcileech-wifi/assets/26452260/1ec78b20-33ac-4a39-856b-c25db778ac57)

**Comment by get1n** [comment]
I have :( @dom0ng 

![regedit](https://github.com/ekknod/pcileech-wifi/assets/99487159/7506560c-fe37-462c-a407-32bc63abe5a9)

**Comment by ekknod** [comment]
> First of all nice release @ekknod :)
> 
> I tried to run your fun - hooker but unfortunately it doens't work; After reinstalling driver it only prints out 640_done: ![fun - hooker_not woorking](https://user-images.githubusercontent.com/99487159/263459728-1a6bfb46-5e36-47d8-b4e5-4131857ef5a2.png)
> 
> settings are: Capture kernel, Enable verbose, Pass-Through and Capture events.
> 
> What am I missing?

fun-hooker is installing PsSetLoadImageNotifyRoutine, that routine is looking for the target driver being loaded and then patches functions to provide debug information.
Could the driver name be different with your system for unknown reason?

**Comment by ekknod** [comment]
I found source code in case someone needs https://pastebin.com/fNnyWKVj
