### ISSUE TITLE
Issue with FPGA PCIe TLP Error Handling

### ISSUE THREAD

**Issue by uk0** [ekknod/pcileech-wifi#9]
Hello ekknod,

Firstly, I would like to extend my gratitude for your efforts in maintaining the pcileech-wifi project. It's been an invaluable resource for the community.

I'm reaching out to report a recurring issue that I've encountered, which I believe might be of significance to other users as well. The issue pertains to an error message that is displayed under certain conditions: "Device Info: FPGA: Bad PCIe TLP received! Should not happen!"

Here's a brief description of the context in which the error occurs:

- 
Thank you for your time and consideration. I'm looking forward to your thoughts and any potential solutions you might suggest.

Best regards,
[github.com/uk0]

**Comment by Alienccc** [comment]
我也是这个问题

**Comment by uk0** [comment]
> 我也是这个问题

我再看看怎么修复 应该可以修复

**Comment by Alienccc** [comment]
> > 我也是这个问题
> 
> 我再看看怎么修复 应该可以修复
有别的联系方式吗

**Comment by uk0** [comment]
升级了bios 解决了
